sankey-beta

source,target,value
Energy,Fossil Fuels,300
Energy,Nuclear,100
Energy,Renewable,250
Fossil Fuels,Electricity,200
Fossil Fuels,Heat,100
Nuclear,Electricity,100
Renewable,Electricity,250
Electricity,Homes,350
Electricity,Industry,200
Heat,Homes,100
