#!/usr/bin/env bun
/**
 * Reads dist/viewer.bundle.js and writes src/viewer/inline.ts with the bundle
 * inlined as a string export. Run via `bun run build:viewer`.
 */
import { readFileSync, writeFileSync } from "node:fs";
import { join, dirname } from "node:path";
import { fileURLToPath } from "node:url";

const __dirname = dirname(fileURLToPath(import.meta.url));
const bundlePath = join(__dirname, "../dist/viewer.bundle.js");
const outputPath = join(__dirname, "../src/viewer/inline.ts");

const bundle = readFileSync(bundlePath, "utf-8");
const content = `// AUTO-GENERATED by scripts/inline-viewer.ts — do not edit directly.
// Run \`bun run build:viewer\` to regenerate after changing src/viewer/index.ts.
export const viewerBundle = ${JSON.stringify(bundle)};
`;

writeFileSync(outputPath, content);
console.log("Generated src/viewer/inline.ts");
